src/main/java/ejbs/LogicBean.java
package ejbs;

import entities.Billdetails;
import entities.Billmaster;
import entities.Customer;
import entities.Product;
import java.util.Collection;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Stateless
public class LogicBean implements LogicBeanLocal {
    
    @PersistenceContext(unitName = "main_pu")
    EntityManager em;
    
    @Override
    public Collection<Customer> getAllCustomer() {
        return em.createNamedQuery("Customer.findAll").getResultList();
    }
    
    @Override
    public Customer getCustomerById(Integer id) {
        Customer customer = (Customer) em.find(Customer.class, id);
        return customer;
    }
    
    @Override
    public Collection<Product> getAllProducts() {
        return em.createNamedQuery("Product.findAll").getResultList();
    }
    
    @Override
    public Product getProductById(Integer id) {
        Product product = (Product) em.find(Product.class, id);
        return product;
    }
    
    @Override
    public void insertIntoBillMaster(Billmaster billMaster) {
        if (billMaster != null) {
            em.persist(billMaster);
        }
    }
    
    @Override
    public void insertIntoBillDetails(Billdetails billDetails) {
        if (billDetails != null) {
            em.persist(billDetails);
        }
    }

    @Override
    public Collection<Billmaster> getBillmasterList() {
        return em.createNamedQuery("Billmaster.findAll").getResultList();
    }

    @Override
    public Collection<Billdetails> getBilldetailsList() {
        return em.createNamedQuery("Billdetails.findAll").getResultList();
    }

    @Override
    public Billmaster getBillMasterById(Integer billId) {
        Billmaster billMaster = (Billmaster) em.find(Billmaster.class, billId);
        return billMaster;
    }

    @Override
    public Collection<Billdetails> getDetailsFromBillmaster(Billmaster billMaster) {
        Collection<Billdetails> bds = em.createNamedQuery("Billdetails.findByBillId").setParameter("billId", billMaster).getResultList();
        return bds;
    }
}

src/main/webapp/jsf/billinfo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>

        <center>
            <div style="margin: 15px 0 15px 0">
                <span>Customer name: </span>
                <h:outputText value="#{custCdi.loggedInCustomer.name}"/><br/>
                <h:outputText value="#{custCdi.currentDate}"/>
            </div>
            <h:dataTable var="data" value="#{custCdi.billDetails}" border="1" cellpadding="6">
                <h:column>
                    <f:facet name="header">Id</f:facet>
                    <h:outputText value="#{data.id}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Product</f:facet>
                    <h:outputText value="#{data.productId.name}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Rate</f:facet>
                    <h:outputText value="#{data.productId.rate}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Quantity</f:facet>
                    <h:outputText value="#{data.quantity}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Amount</f:facet>
                    <h:outputText value="#{data.total}"/>
                </h:column>
            </h:dataTable>
            <h:panelGrid columns="2" cellpadding="6">
                <h:outputText value="Gross total: "/>
                <h:outputText value="#{custCdi.bm.grossTotal} Rs."/>
            </h:panelGrid>
            <h:form>
                <h:commandLink value="Go to store" action="#{custCdi.redirect('store.jsf')}"/>
            </h:form>
        </center>
    </h:body>
</html>

src/main/webapp/jsf/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <center>
                <h:panelGrid columns="2" border="1">
                    <f:facet name="header">Customer login</f:facet>
                    <h:outputLabel for="customerId" value="Enter customer id: "/>
                    <h:inputText id="customerId" required="true" requiredMessage="Customer id required to login the customer" value="#{custCdi.loggedInCustomer.id}"/>
                    <f:facet name="footer">
                        <center>
                            <h:commandButton value="Login" action="#{custCdi.doLogin()}"/>
                        </center>
                    </f:facet>                    
                </h:panelGrid>
            </center>
        </h:form>
    </h:body>
</html>

src/main/webapp/jsf/orders.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <center>
            <h:form>
            <h:dataTable var="data" value="#{custCdi.billmasterList}" border="1" cellpadding="6">
                <h:column>
                    <f:facet name="header">Bill_Id</f:facet>
                    <h:outputText value="#{data.id}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Customer</f:facet>
                    <h:outputText value="#{data.customerId.name}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Gross_Total</f:facet>
                    <h:outputText value="#{data.grossTotal}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Order details</f:facet>
                    <h:commandButton value="View order" action="#{custCdi.doOrderDetails(data.id)}"/>
                </h:column>
            </h:dataTable>
            </h:form>
        </center>        
    </h:body>
</html>

src/main/webapp/jsf/store.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <center>
            <h1>Welcome #{custCdi.loggedInCustomer.name}</h1>
            <h:form>
                <h:dataTable value="#{custCdi.store}" var="data" border="1" cellpadding="6">

                    <f:facet name="caption"><span style="font-size: 20px; font-weight: bolder">Purchase products</span></f:facet>
                    <h:column>
                        <f:facet name="header">Id</f:facet>
                        <h:outputText value="#{data.id}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">Name</f:facet>
                        <h:outputText value="#{data.name}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">Rate</f:facet>
                        <h:outputText value="#{data.rate}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">Stock</f:facet>
                        <h:outputText value="#{data.stock}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">Discount</f:facet>
                        <h:outputText value="#{data.discount}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">Add to kart</f:facet>
                        <h:selectManyCheckbox value="#{custCdi.kart}">
                            <f:selectItem itemValue="#{data}" itemLabel=""/>
                        </h:selectManyCheckbox>
                    </h:column>
                    <h:column>
                        <f:facet name="header">Quantity</f:facet>
                        <h:inputText value="#{custCdi.quantities}"/>
                    </h:column>
                </h:dataTable>
                <div style="margin: 10px">
                    <h:panelGrid columns="2" cellpadding="6">
                        <h:commandButton value="Place order" action="#{custCdi.doPlaceOrder()}"/>
                        <h:link value="Goto bill list" outcome="orders"/>
                    </h:panelGrid>
                </div>
            </h:form>
        </center>
    </h:body>
</html>